USE_COVER_HED: false
DOC_URL: https://docs.google.com/document/d/1OJLCPW8FgAetQchg_53hNmaPSnCPl7E-xdhARsPCzx8/edit

PART1_LINK: index-1.html
PART2_LINK: index-2.html
PART3_LINK: index-3.html

PART1_LINK_OLD: https://www.columbiaspectator.com/eye-lead/2019/10/23/is-columbias-department-system-ready-to-evolve/
PART2_LINK_OLD: https://www.columbiaspectator.com/eye-lead/2019/10/23/is-columbias-department-system-ready-to-evolve/
PART3_LINK_OLD: https://www.columbiaspectator.com/eye-lead/2019/10/23/is-columbias-department-system-ready-to-evolve/
