USE_COVER_HED: false
DOC_URL: https://docs.google.com/document/d/1Sba5SfdWovkDL2bfPSB2xKdXSSetbh-AxhhoHdpCZsk/edit

PART1_LINK: https://www.columbiaspectator.com/eye-lead/2019/11/15/students-and-faculty-say-gender-based-harassment-and-discrimination-at-columbia-is-systemic-why-are-they-turning-away-from-the-system-built-to-address-it
PART2_LINK: https://www.columbiaspectator.com/eye-lead/2019/11/15/eoaa-harassment-discrimination-title-ix-part-2
PART3_LINK: https://www.columbiaspectator.com/eye-lead/2019/11/15/eoaa-harassment-discrimination-title-ix-part-3

